[remnawave]
base_url = "https://your-remnawave-panel.com"
token = "your-api-token-here"

[telegram]
bot_token = "1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZ"
chat_id = 123456789
custom_emoji = true # Requires TG Premium from the bot creator
# message_thread_id = 42

[watcher]
interval = 3600
concurrency = 3

sources = ["services", "geoip", "stash"]  # Excluded CDN
state_file = "data/state.json"

[logging]
level = 20
format = "[%(levelname)s] %(asctime)s - %(name)s - %(message)s"
